import {
  Upload,
  X,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ChevronsUpDown,
  Plus,
  Minus,
  Trash,
  Pencil,
  Settings,
  User,
  Mail,
  Lock,
  Eye,
  EyeOff,
  Moon,
  Sun,
  Laptop,
  Search,
  Filter,
  MoreVertical,
  MoreHorizontal,
  Image,
  Camera,
  Loader2,
  AlertCircle,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  InfoIcon,
  type LucideIcon,
  LogOut,
  Home,
  Shirt,
  Palette,
  Sparkles,
  Languages,
  Bell,
  Shield,
  UserCircle,
  Grid,
  List,
  Share,
  Download,
  Save,
  Copy,
  Clipboard,
  ClipboardCheck,
  Heart,
  Star,
  Bookmark,
  Calendar,
  Clock,
  History,
  Undo,
  Redo,
  RefreshCw,
  RotateCcw,
  RotateCw,
  ZoomIn,
  ZoomOut,
  Move,
  Maximize2,
  Minimize2,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ExternalLink,
  Link,
  Unlink,
  Tag,
  Hash,
  AtSign,
  MapPin,
  Phone,
  Send,
  MessageSquare,
  HelpCircle,
  FileText,
  Files,
  Folder,
  FolderOpen,
  Archive,
  Package,
  Scale,
  Ruler,
  Scissors,
  Paintbrush,
  Watch,
  Droplets,
  Gauge,
  SlidersHorizontal,
  ToggleLeft,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  // Essential UI
  spinner: Loader2,
  close: X,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronsUpDown: ChevronsUpDown,
  plus: Plus,
  minus: Minus,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  maximize: Maximize2,
  minimize: Minimize2,
  move: Move,

  // Actions
  edit: Pencil,
  delete: Trash,
  settings: Settings,
  search: Search,
  filter: Filter,
  more: MoreVertical,
  moreHorizontal: MoreHorizontal,
  upload: Upload,
  download: Download,
  save: Save,
  share: Share,
  copy: Copy,
  clipboard: Clipboard,
  clipboardCheck: ClipboardCheck,
  refresh: RefreshCw,
  undo: Undo,
  redo: Redo,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  send: Send,

  // Authentication & User
  user: User,
  userCircle: UserCircle,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  logout: LogOut,
  phone: Phone,
  atSign: AtSign,

  // Theme & Customization
  moon: Moon,
  sun: Sun,
  system: Laptop,
  brush: Paintbrush,
  watch: Watch,
  droplet: Droplets,
  palette: Palette,
  sliders: SlidersHorizontal,
  gauge: Gauge,
  toggle: ToggleLeft,

  // Media & Files
  image: Image,
  camera: Camera,
  fileText: FileText,
  files: Files,
  folder: Folder,
  folderOpen: FolderOpen,
  archive: Archive,

  // Feedback & Status
  loading: Loader2,
  error: XCircle,
  warning: AlertTriangle,
  success: CheckCircle2,
  info: InfoIcon,
  alert: AlertCircle,
  help: HelpCircle,

  // Navigation & Links
  home: Home,
  wardrobe: Shirt,
  tryOn: Sparkles,
  language: Languages,
  notifications: Bell,
  security: Shield,
  externalLink: ExternalLink,
  link: Link,
  unlink: Unlink,
  mapPin: MapPin,

  // Layout & Organization
  grid: Grid,
  list: List,
  tag: Tag,
  hash: Hash,
  package: Package,

  // Social & Interaction
  heart: Heart,
  star: Star,
  bookmark: Bookmark,
  messageSquare: MessageSquare,

  // Time & History
  calendar: Calendar,
  clock: Clock,
  history: History,

  // Clothing & Measurements
  scale: Scale,
  ruler: Ruler,
  scissors: Scissors,
} as const;
